### ISSUE TITLE
Program crashes when data is too big for audio files

### ISSUE THREAD

**Issue by aixoio** [scott-mescudi/stegano#7]
Hi, I just got this error when using both `EmbedIntoWAVWithDepth` and `EmbedIntoWAVAtDepth` functions and it looks to me that this does not check if the data is too big to embed because when embedding files that are too big it crashes and panics. Here is the error log:
```
panic: runtime error: index out of range [19640320] with length 19640320

goroutine 106 [running]:
github.com/scott-mescudi/stegano/pkg.EmbedDataWithDepthAudio(0x1400214a0f0, {0x14005220000, 0x2d56e9, 0x105356cd0?}, 0x0)
        /Users/[ME]/go/pkg/mod/github.com/scott-mescudi/stegano@v1.7.6/pkg/audio.go:60 +0x230
github.com/scott-mescudi/stegano.(*AudioEmbedHandler).EmbedIntoWAVWithDepth(0x14000994e98?, {0x14002de0060, 0x28}, {0x14017988000, 0x94}, {0x14017c80000?, 0x2f3938ed2f0a002a?, 0x3917122f331138ed?}, 0x0)
        /Users/[ME]/go/pkg/mod/github.com/scott-mescudi/stegano@v1.7.6/audio.go:27 +0x90
main.render_stegano_audio_embed.func2.1(0x1400323ca48?)
        /Users/[ME]/Documents/Projects/aixoio-privacy-tools/render_stegano_audio_embed.go:111 +0x4b8
created by main.render_stegano_audio_embed.func2 in goroutine 40
        /Users/[ME]/Documents/Projects/aixoio-privacy-tools/render_stegano_audio_embed.go:74 +0x204
```

I think this could be prevented with a check in the functions I mentioned to see if the data is too big and if it is, return an error.

**Comment by scott-mescudi** [comment]
@aixoio  i just pushed a fix with some tests

**Comment by aixoio** [comment]
Ok thank you

**Comment by aixoio** [comment]
@scott-mescudi This is not fixed I have just tested the new fix and I get this error:
```
19640320
panic: runtime error: index out of range [19640320] with length 19640320

goroutine 6 [running]:
github.com/scott-mescudi/stegano/pkg.EmbedDataWithDepthAudio(0x14002de2120, {0x140060c8000, 0x5c77c3, 0x100a42c70?}, 0x0)
        /Users/[ME]/go/pkg/mod/github.com/scott-mescudi/stegano@v1.7.7-0.20250121092839-5ea634e6606f/pkg/audio.go:73 +0x2b0
github.com/scott-mescudi/stegano.(*AudioEmbedHandler).EmbedIntoWAVWithDepth(0x14000089e98?, {0x14002d64330, 0x28}, {0x140018dc5a0, 0x94}, {0x14008986000?, 0x140001545e8?, 0x1006343fc?}, 0x0)
        /Users/[ME]/go/pkg/mod/github.com/scott-mescudi/stegano@v1.7.7-0.20250121092839-5ea634e6606f/audio.go:27 +0x90
main.render_stegano_audio_embed.func2.1(0x140002be938?)
        /Users/[ME]/Documents/Projects/aixoio-privacy-tools/render_stegano_audio_embed.go:111 +0x4b8
created by main.render_stegano_audio_embed.func2 in goroutine 29
        /Users/[ME]/Documents/Projects/aixoio-privacy-tools/render_stegano_audio_embed.go:74 +0x204
exit status 2
```

**Comment by scott-mescudi** [comment]
@aixoio try v1.7.7

**Comment by aixoio** [comment]
@scott-mescudi Ok i am now

**Comment by aixoio** [comment]
@scott-mescudi  Ok I just tried v1.7.7, it still panics

**Comment by scott-mescudi** [comment]
@aixoio what is the size of the data and what is the size of the image? I'll use it as a test case

**Comment by aixoio** [comment]
@scott-mescudi the wav audio file (cover file) is 39.4MB (39357454 bytes) and the file to embed is 6.1MB (6063398 bytes)

**Comment by aixoio** [comment]
@scott-mescudi Everything is fixed just tested it in my code works well. Thank you for fixing this.
